<html>
    <head>
        <meta charset="utf-8">
        <title>KasterTool</title>
        <link rel="stylesheet" type="text/css" href="../css/cssPortada.css">
    </head>
    <body>
        <header id="cabeceraGeneral">
            <nav id="MenuCabecera">
                <div>
                    <ul id="menu">
                        <li>Home</li>
                        <li>Registro</li>
                        <li>PCs</li>
                        <li>Periféricos</li>
                        <li>SmartPhones</li>
                        <li>Televisores</li>
                        <li>Pedido</li>
                        <li>Contacto</li>
                    </ul>
                    <div id="divForm">
                        <form action="#" method="GET">
                            <table>
                                <tr>
                                    <td><input type="text" id="buscador" placeholder="Buscador" name="buscador"></td>
                                    <td><input type="submit" value="&#128269;" name="botonBuscar" id="busqueda"></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                    <div id="logo">
                        <img src="../images/logoK.png">
                    </div>
                </div>
            </nav>
            <div id="medioFondo">
                <img src="../images/fondo1.jpg">
            </div>        
        </header>