<html>
    <head>
        <meta charset="utf-8">
        <title>KasterTool</title>
        <link rel="stylesheet" type="text/css" href="../css/cssGeneral.css">
    </head>
    <body>
        <header id="cabeceraGeneral">
            <nav id="MenuCabecera">
                <div>
                    <ul id="menu">
                        <a href="../arranque/portada.php"><li>Home</li></a>
                        <a href="../php/pcs.php"><li>PCs</li></a>
                        <a href="../php/perifericos.php"><li>Periféricos</li></a>
                        <a href="../php/smartphones.php"><li>SmartPhones</li></a>
                        <a href="../php/registros.php"><li>Registro</li></a>
                        <a href="../php/pedidos.php"><li>Pedidos</li></a>
                        
                    </ul>
                    <div id="divForm">
                        <form action="#" method="GET">
                            <table>
                                <tr>
                                    <td><input type="text" id="buscador" placeholder="Buscador" name="buscador"></td>
                                    <td><input type="submit" value="&#128269;" name="botonBuscar" id="busqueda"></td>
                                </tr>
                            </table>
                        </form>
                    </div>
                    <div id="logo">
                        <img src="../images/logoK.png">
                    </div>
                </div>
            </nav>
            <div id="medioFondo">
                <img src="../images/fondo1.jpg">
            </div>        
        </header>